name: Request a POC
description: Request POC for a new customer.
title: "[POC]: "
labels: ["poc", "engineering"]
# projects: ["bloo-team/30", "bloo-team/12"]
assignees:
  - shomiron
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this POC request! To address this as fast as possible, we need some information.
  - type: input
    id: customer-name
    attributes:
      label: Customer Name
      placeholder: WayneCorp
    validations:
      required: true
  - type: input
    id: cluster-name
    attributes:
      label: Cluster Name
      placeholder: WayneCorp
    validations:
      required: true
  - type: dropdown
    id: region
    attributes:
      label: Region
      options:
        - India
        - US
      default: 0
    validations:
      required: true
  - type: input
    id: license-volume
    attributes:
      label: License Volume
      placeholder: 100 GB/Day
    validations:
      required: true
  - type: dropdown
    id: overage-allowed
    attributes:
      label: Overage Allowed
      options:
        - "Yes"
        - "No"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: license-plan
    attributes:
      label: License Plan
      options:
        - Professional
        - Entereprise
        - Essential
      default: 0
    validations:
      required: true
  - type: textarea
    id: devices-list
    attributes:
      label: List of devices to integrate
      placeholder: Windows servers, Sophos firewall, AD and Linux Servers.
    validations:
      required: false
  - type: input
    id: start-date
    attributes:
      label: Setup Start Date
      placeholder: 2nd July 2024
    validations:
      required: true
  - type: checkboxes
    id: log-source
    attributes:
      label: Customer Log Source (Multi Select)
      options:
        - label: PICO
        - label: DS
      
